name: File Handoff
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Crates file
        run: |
          echo " creating file " > app.txt
          uname -a >> app.txt
      - name: uploading file
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: app.txt
  verify:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download app package
          uses: actions/download-artifact@v4
          with:
            name: app-package

        - name: verify app
          run: test -f app.txt
