name: Second Workflow
on: push
jobs:
  Second:
    runs-on: ubuntu-latest
    steps:
      - name: checkut repo
        uses: actions/checkout@v4
      - name: Print kernal details
        run: |
          uname -a
          ls -la
      - name: No of files
        run: find . -type f | wc -l

