name: Release Pipeline
on: push
jobs:
  notify:
    uses: ./.github/workflows/notify.yml
    with:
      environment: Production
    secrets:
      NOTIFY_TOKEN: ${{ secrets.NOTIFY_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: echo " Running lint "
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        run: echo " Running Unit tests "
  package:
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]
    steps:
      - name: Package
        run: echo " Lint and unit tests passed "
