name: Secrets check
on: push
jobs:
  Secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check App_Token
        env:
          APP_TOKEN: ${{secrets.APP_TOKEN}}
        run: |
          if [-n "$APP_TOKEN"]; then
           echo " APP_TOKEN is set and available "
          else
           echo "APP_TOKEN is not set"
           exit 1
          fi         
