name: secure workflow
on: push
permissions:
  contents: read
jobs:
  secure:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: list repo files
        run: ls -la
